### ISSUE TITLE
Could not read /home/docker/.composer/auth.json

### ISSUE THREAD

**Issue by vibby** [jmleroux/covid-attestation#16]
Hello :)

J’ai tenté de monter l’appli mais j’ai une erreur sur le make setup :
```
 [RuntimeException]                                                                             
  Could not read /home/docker/.composer/auth.json                                                                                                                                             
  file_get_contents(/home/docker/.composer/auth.json): failed to open stream: Permission denied  
```

Ce fichier n’existe pas chez moi, qu’est ce qu’il doit contenir ?

**Comment by vibby** [comment]
Bon finalement j,ai fait le ```composer install``` puis ```docker-compose up``` moi-même :P

**Comment by jmleroux** [comment]
Bonsoir,
Cela peut varier suivant les distributions Linux, et je ne sais même pas ce qu'il en est sur Mac ou Windows :)

C'est pourquoi j'ai bougé ces settings dans un fichier d'override à personnaliser: https://github.com/jmleroux/covid-attestation/pull/20
